from PySide6.QtWidgets import QWidget, QVBoxLayout, QHBoxLayout, QLabel, QPushButton, QTextBrowser, QMessageBox
from PySide6.QtCore import Qt
from workers.ai_thread import AIWorker

class AIPage(QWidget):
    """
    The AIPage provides a user interface to request and display 
    the feedback generated by the artificial intelligence (Gemini) on the portfolio.
    """
    def __init__(self):
        """Initializes the AIPage, sets up the UI, and prepares for background data loading."""
        super().__init__()
        # Cache for the data coming from the simulation (mu, sigma, scenarios, etc.)
        self.portfolio_data = None
        self.worker = None
        self.setup_ui()

    def setup_ui(self):
        """Sets up the user interface components of the AIPage, including a header, a button to trigger the AI analysis, and a QTextBrowser to display the results."""
        main_layout = QVBoxLayout(self)
        main_layout.setSpacing(20)
        main_layout.setContentsMargins(28, 24, 28, 24)

        # ── HEADER ───────────────────────────────────────────
        header_label = QLabel("AI Portfolio Insights")
        header_label.setObjectName("page_header")
        main_layout.addWidget(header_label)

        # ── CONTROLS BAR ─────────────────────────────────────
        controls_layout = QHBoxLayout()
        
        self.analyze_btn = QPushButton("Generate AI Analysis")
        self.analyze_btn.setObjectName("primary_btn")
        self.analyze_btn.setMinimumHeight(38)
        self.analyze_btn.setMinimumWidth(180)
        self.analyze_btn.setToolTip("Requests a detailed portfolio analysis from Gemini")
        self.analyze_btn.clicked.connect(self.on_analyze_clicked)
        # Disabled by default until we receive data from the simulation
        self.analyze_btn.setEnabled(False)

        controls_layout.addWidget(self.analyze_btn)
        controls_layout.addStretch()
        main_layout.addLayout(controls_layout)

        # ── OUTPUT DISPLAY ───────────────────────────────────
        section_label = QLabel("ARTIFICIAL INTELLIGENCE REPORT")
        section_label.setObjectName("section_label")
        main_layout.addWidget(section_label)

        self.report_display = QTextBrowser()
        self.report_display.setOpenExternalLinks(True)
        # Apply inline style to blend it with the Dark/Bloomberg theme defined in style.qss
        self.report_display.setStyleSheet("""
            QTextBrowser {
                background-color: #111820;
                border: 1px solid #1E2733;
                border-radius: 6px;
                padding: 16px;
                color: #C8D0DC;
                font-size: 14px;
                line-height: 1.5;
            }
        """)
        
        # Default text
        self.report_display.setHtml(
            "<p style='color: #5A6878; font-style: italic;'>"
            "Run a Monte Carlo Simulation first to gather the necessary data, "
            "then click on 'Generate AI Analysis' to get the report."
            "</p>"
        )
        main_layout.addWidget(self.report_display)

    def set_portfolio_data(self, data: dict):
        """
        Public method that the MainWindow calls when the simulation data is ready.
        """
        self.portfolio_data = data
        
        # Automatically trigger the analysis without waiting for the user to click!
        self.on_analyze_clicked()

    def on_analyze_clicked(self):
        """Triggered when the user clicks the 'Generate AI Analysis' button. It starts the background worker to fetch insights from the Gemini API."""
        if not self.portfolio_data:
            QMessageBox.warning(self, "Missing Data", "There is no portfolio data to analyze.")
            return

        # SAFETY CHECK: Prevent launching multiple API calls if the user 
        # clicks "Run Simulation" on the Monte Carlo page multiple times rapidly.
        if self.worker is not None and self.worker.isRunning():
            print("[UI DEBUG] AI analysis is already running in the background. Skipping duplicate request.")
            return

        self.analyze_btn.setEnabled(False)
        self.analyze_btn.setText("Analysis in progress...")
        
        # Show a loading state in the text browser
        self.report_display.setHtml(
            "<p style='color: #F0A500; font-size: 15px; font-weight: bold;'>"
            "Connecting to AI. Generating insights...</p>"
        )

        # Start the background worker
        self.worker = AIWorker(self.portfolio_data)
        self.worker.analysis_fetched.connect(self.on_analysis_complete)
        self.worker.error_occurred.connect(self.on_error)
        self.worker.start()

    def on_analysis_complete(self, result: dict):
        """Formats the JSON returned by the AI into readable HTML."""
        self.analyze_btn.setEnabled(True)
        self.analyze_btn.setText("Refresh AI Analysis")
        
        html_content = ""
        
        # This rendering logic depends on the exact JSON structure 
        # defined in your prompts.json. Here is a robust generic parser:
        for key, value in result.items():
            formatted_key = key.replace("_", " ").title()
            
            if isinstance(value, list):
                html_content += f"<h3 style='color: #E8EDF5;'>{formatted_key}</h3><ul>"
                for item in value:
                    html_content += f"<li style='margin-bottom: 8px;'>{item}</li>"
                html_content += "</ul>"
            elif isinstance(value, dict):
                html_content += f"<h3 style='color: #E8EDF5;'>{formatted_key}</h3><ul style='list-style-type: none; padding-left: 0;'>"
                for sub_key, sub_val in value.items():
                    html_content += f"<li style='margin-bottom: 6px;'><b>{sub_key}:</b> {sub_val}</li>"
                html_content += "</ul>"
            else:
                html_content += f"<h3 style='color: #E8EDF5;'>{formatted_key}</h3><p>{value}</p>"

        self.report_display.setHtml(html_content)

    def on_error(self, error_msg):
        """Handles errors by re-enabling the analyze button and displaying the error message in the text browser."""
        self.analyze_btn.setEnabled(True)
        self.analyze_btn.setText("Retry Analysis")
        self.report_display.setHtml(f"<p style='color: #E05252;'><b>Error:</b> {error_msg}</p>")
        QMessageBox.critical(self, "AI Error", f"An error occurred:\n{error_msg}")